name = "coffre"
main = "worker/index.js"
compatibility_date = "2026-08-07"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "coffre-db"
database_id = "2bc99ebc-e1c9-40b1-bfcb-1599afce450a"
